<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\AgriERP.BuildingBlocks.Infrastructure\AgriERP.BuildingBlocks.Infrastructure.csproj" />
    <ProjectReference Include="..\AgriERP.Modules.Weather.Application\AgriERP.Modules.Weather.Application.csproj" />
    <ProjectReference Include="..\AgriERP.Modules.Weather.Domain\AgriERP.Modules.Weather.Domain.csproj" />
  </ItemGroup>

</Project>
