<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Auth\AgriERP.Modules.Auth.Presentation\AgriERP.Modules.Auth.Presentation.csproj" />
    <ProjectReference Include="..\AgriERP.Modules.Finance.Application\AgriERP.Modules.Finance.Application.csproj" />
  </ItemGroup>

</Project>
