<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.9" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\AgriERP.BuildingBlocks.Application\AgriERP.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\..\Inventory\AgriERP.Modules.Inventory.Infrastructure\AgriERP.Modules.Inventory.Infrastructure.csproj" />
    <ProjectReference Include="..\AgriERP.Modules.Livestock.Domain\AgriERP.Modules.Livestock.Domain.csproj" />
  </ItemGroup>

</Project>
